name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v3
        with:
          install: true
      - name: Run CI
        shell: bash
        run: |
          eval "$(mise env -s bash)"
          make ci
